### ISSUE TITLE
ports vs port ?!

### ISSUE THREAD

**Issue by pandorasNox** [utopia-planitia/dnslb#1]
https://github.com/utopia-planitia/dnslb/blob/ed948953c9fc3c6e5a2a889350f41823c631a02c/cmd/dnslb/main.go#L37

should this be `port` instead of `ports` or up where the flag is defined should be change to `ports`?

**Comment by damoon** [comment]
thanks. good catch.

this was a last change before calling it good... https://github.com/utopia-planitia/dnslb/commit/ed948953c9fc3c6e5a2a889350f41823c631a02c
